/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 model.glb --transform --shadows 
Files: model.glb [4.97MB] > model-transformed.glb [149.47KB] (97%)
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { editable as e } from '@theatre/r3f';
export function Model(props) {
  const { nodes, materials } = useGLTF('/models/model-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['growth-by-design'].geometry}
        material={materials.PaletteMaterial001}
        position={[-0.005, 0.087, -0.002]}
        scale={0.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass.geometry}
        material={materials.PaletteMaterial002}
      />
    </group>
  );
}

useGLTF.preload('/model-transformed.glb');
